//! Skill template generation for Claude Code.
//!
//! Generates skill directories in `.claude/skills/` with SKILL.md files
//! and optional supporting files. Skills provide auto-invocation and
//! richer context than slash commands.
//!
//! Skills coexist with slash commands (`.claude/commands/`) — both are
//! generated during `writ init` for maximum compatibility. Slash commands
//! serve older Claude Code versions; skills add auto-invocation and
//! supporting files. Neither replaces the other for beta.

use std::fs;
use std::path::Path;

use crate::error::WritResult;
use crate::fsutil::atomic_write;

/// Header injected at the top of every generated skill file.
const GENERATED_HEADER: &str = "<!-- Generated by writ init. Do not edit. -->\n";

/// A supporting file bundled with a skill (e.g., checklists, guides).
pub struct SupportingFile {
    /// File name (e.g., "reading-context.md").
    pub filename: &'static str,
    /// Markdown content (without the generated header).
    pub content: &'static str,
}

/// A skill template: directory name, SKILL.md content, and supporting files.
pub struct SkillTemplate {
    /// Directory name under `.claude/skills/`, e.g. "writ-context".
    pub name: &'static str,
    /// SKILL.md content including YAML frontmatter (without the generated header).
    pub skill_md: &'static str,
    /// Supporting files to generate alongside SKILL.md.
    pub supporting_files: &'static [SupportingFile],
}

// ---------------------------------------------------------------------------
// Tier 1: Auto-Invoking Skills (3) — SK.3 (CC)
//
// These are the core agent workflow skills. They auto-invoke at the right
// moments so agents don't need explicit instructions to use writ.
//
// The writ-context skill implements the agent-first spec flow from
// docs/briefs/writ-agent-first-specs.md (Sampson design):
//   1. Check for assigned spec → continue working
//   2. Check for unclaimed specs → claim one matching your task
//   3. No specs → create one from your task description
// ---------------------------------------------------------------------------

const WRIT_CONTEXT_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-context",
    skill_md: r#"---
name: "writ-context"
description: "Understand the current project state, your assigned task, and recent activity"
autoInvoke: true
context: inline
---

# Writ Context

Run this FIRST at the start of every task.

## Command

```bash
writ context
```

## After Running Context

1. **Check if you have an assigned spec** (look for `assigned_spec` or your agent ID in a spec's `claimed_by`):
   - If yes: you already have a task. Continue working on it.
   - Seal your progress with `writ seal -s "what you did"`.

2. **Check for unclaimed specs** (the `unclaimed_specs` section):
   - If unclaimed specs exist: claim the one that matches your task.
   - Run: `writ spec claim <id>`

3. **If no assigned spec and no unclaimed specs**:
   - Create a spec from your task: `writ spec add "brief description of your task"`
   - Use a short summary (5-10 words), not your full prompt.
   - Writ generates the ID automatically.

4. Once you have a spec, begin working. Seal your progress with `writ seal -s "what you did"`.

## When to Re-Run Context

- After completing a major piece of work (check for new activity from other agents)
- If you're unsure about the current project state
- Before starting a new sub-task within your spec

## Output Format

Context returns data in TOON format (token-optimized, 20-33% smaller than JSON).
Key fields: `specs` (task status), `recent_seals` (recent activity), `integration_risk` (contention warnings).
"#,
    supporting_files: &[SupportingFile {
        filename: "reading-context.md",
        content: r#"# Reading Writ Context Output

A field-by-field guide to understanding `writ context` output.

## Key Fields

### `specs`
Lists all active specs with status, claimed_by, and seal count.
- `Pending` — created but no agent has started work
- `InProgress` — an agent is actively working (has seals)
- `Complete` — agent called `writ spec done`

### `unclaimed_specs`
Specs with no `claimed_by` agent. If one matches your task, claim it instead of creating a new one.

### `recent_seals`
The latest seals from all agents. Shows what changed recently.
- Check for file overlaps with your work
- If another agent modified files you're about to touch, re-read those files

### `integration_risk`
Risk assessment for concurrent work:
- `low` — minimal overlap, safe to proceed
- `medium` — some shared files, be aware
- `high` — significant overlap, check recent seals before editing shared files

### `unsealed_changes`
Files you've modified since your last seal. If this is non-empty, consider sealing before checking context.
"#,
    }],
};

const WRIT_SEAL_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-seal",
    skill_md: r#"---
name: "writ-seal"
description: "Checkpoint your current work as an immutable snapshot"
autoInvoke: true
context: inline
---

# Writ Seal

Create a checkpoint after each meaningful unit of work.

## Command

```bash
writ seal -s "what you accomplished"
```

The `--spec` flag is optional if you have exactly one claimed spec (auto-scoped).

## When to Seal

- After implementing a feature or fixing a bug
- After making a set of related changes across multiple files
- Before switching to a different part of your task
- After running tests (include results with `--tests-passed N --tests-failed M`)

## Writing Good Summaries

Be specific about WHAT changed, not HOW:
- Good: "Added OAuth2 login endpoint with JWT token generation"
- Bad: "Made changes to auth module"
- Good: "Fixed null pointer in payment validation for zero-amount transactions"
- Bad: "Bug fix"

## Options

- `-s "summary"` — clear description of what you accomplished (required)
- `--spec <id>` — the spec this work belongs to (optional if you have one claimed spec)
- `--tests-passed N --tests-failed M` — test results for this checkpoint
- `--paths file1,file2` — seal specific files only (default: all changes)
"#,
    supporting_files: &[SupportingFile {
        filename: "seal-checklist.md",
        content: r#"# Pre-Seal Checklist

Before sealing, verify:

1. **Changes are coherent** — the seal represents one logical unit of work
2. **No debug artifacts** — remove console.log, print statements, TODO comments meant for yourself
3. **Files are saved** — all modified files are written to disk
4. **Summary is descriptive** — someone reading the seal log should understand what changed
5. **Tests run (if applicable)** — include `--tests-passed N --tests-failed M` when you have test results

## After Sealing

- Check the seal output for `hints` — writ may suggest actions
- Check `file_scope_warning` — you may have modified files outside your spec's expected scope
- If the seal shows 0 file changes, you have no new modifications since your last seal
"#,
    }],
};

const WRIT_SPEC_DONE_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-spec-done",
    skill_md: r#"---
name: "writ-spec-done"
description: "Mark your task as complete when all requirements are met"
autoInvoke: true
context: inline
---

# Writ Spec Done

Mark your spec as complete when your task is fully finished.

## Command

```bash
writ spec done
```

The spec ID is optional if you have exactly one claimed spec (auto-scoped).
Add a summary: `writ spec done -s "what was accomplished"`

## When to Call Spec Done

- All requirements of your task are met
- Code changes are complete and working
- Tests pass (if applicable)

Do NOT call spec done if:
- You still have pending work on this task
- Tests are failing
- You're planning to make more changes

## What Happens After Spec Done

1. Your spec status changes to `Complete`
2. Writ checks if other completed specs overlap with yours
3. If overlap exists, convergence runs automatically (merges your work with others)
4. The merged result is stored in writ's object store (no disk changes yet)
5. When the user runs `writ finish`, your converged work is committed to git

You do NOT need to run `writ finish` — that's the user's job.
"#,
    supporting_files: &[SupportingFile {
        filename: "completion-checklist.md",
        content: r#"# Completion Checklist

Before marking your spec as done, verify:

1. **Task requirements met** — your original task is fully addressed
2. **Code is functional** — changes work as intended
3. **No partial implementations** — don't leave stub functions or TODO markers
4. **Final seal created** — your latest changes are sealed (spec done creates a completion seal, but your work seal should be recent)
5. **Tests pass** — if your changes are testable, verify they pass

## After Spec Done

- Your work is now eligible for convergence with other agents' work
- The user will run `writ finish` to commit everything to git
- You can start a new task by creating a new spec, or your session is complete
"#,
    }],
};

// ---------------------------------------------------------------------------
// Tier 2: Status & Review Skills (4) — SK.4 (Izzy)
// ---------------------------------------------------------------------------

const WRIT_STATUS_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-status",
    skill_md: r#"---
name: "writ-status"
description: "Show the project dashboard with all specs, agents, and convergence state"
---

# Writ Status

View the project dashboard showing all specs, agents, and progress.

## Command

```bash
writ status
```

## What It Shows

- All specs with status (in-progress, complete), owner agent, and seal counts
- File contention warnings (files modified by multiple specs)
- Convergence state (pending, completed, conflicts)
- Unsealed changes in the working directory

Use this to get a quick overview of project progress without the full context output.
"#,
    supporting_files: &[],
};

const WRIT_DIFF_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-diff",
    skill_md: r#"---
name: "writ-diff"
description: "Show changes since the last seal or between seals"
---

# Writ Diff

View what has changed since your last seal.

## Command

```bash
writ diff                     # changes since last seal
writ diff --spec <id>         # changes for a specific spec
writ diff <seal-id>           # changes in a specific seal
```

Use this before sealing to review your work, or to inspect what another agent changed.
"#,
    supporting_files: &[],
};

const WRIT_LOG_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-log",
    skill_md: r#"---
name: "writ-log"
description: "Show the seal history for this project"
---

# Writ Log

View the seal history.

## Command

```bash
writ log                      # recent seals (default limit)
writ log --limit 10           # last 10 seals
writ log --spec <id>          # seals for a specific spec only
writ log --all                # all seals including diverged branches
```

Use `--all` to see the full history across all specs and convergence seals.
"#,
    supporting_files: &[],
};

const WRIT_SHOW_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-show",
    skill_md: r#"---
name: "writ-show"
description: "Show details of a specific seal including changes and metadata"
---

# Writ Show

Inspect a specific seal's full details.

## Command

```bash
writ show <seal-id>           # show seal metadata and file list
writ show <seal-id> --diff    # show seal with file diffs
```

Shows: summary, agent identity, spec, timestamp, file changes, verification status, and test results (if recorded).
"#,
    supporting_files: &[],
};

// ---------------------------------------------------------------------------
// Tier 3: Spec Management Skills (3) — SK.4 (Izzy)
// ---------------------------------------------------------------------------

const WRIT_SPEC_STATUS_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-spec-status",
    skill_md: r#"---
name: "writ-spec-status"
description: "List all specs and their current status"
---

# Writ Spec Status

View all specs in the project.

## Command

```bash
writ spec status
```

Shows each spec's ID, summary, status (Pending/InProgress/Complete), owning agent, seal count, and creation time.
"#,
    supporting_files: &[],
};

const WRIT_SPEC_SHOW_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-spec-show",
    skill_md: r#"---
name: "writ-spec-show"
description: "Show detailed information about a specific spec"
---

# Writ Spec Show

Inspect a specific spec's full details.

## Command

```bash
writ spec show <spec-id>
```

Shows: summary, status, claimed-by agent, file list, seal history, genesis tree snapshot, and commit state.
"#,
    supporting_files: &[],
};

const WRIT_SPEC_REOPEN_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-spec-reopen",
    skill_md: r#"---
name: "writ-spec-reopen"
description: "Reopen a completed spec for additional work"
---

# Writ Spec Reopen

Reopen a spec that was marked as complete.

## Command

```bash
writ spec reopen <spec-id>
```

Use this when you realize more work is needed after calling `writ spec done`. The spec returns to InProgress status and you can continue sealing against it.
"#,
    supporting_files: &[],
};

// ---------------------------------------------------------------------------
// Tier 3: Workspace Skills (2) — SK.4 (Izzy)
// ---------------------------------------------------------------------------

const WRIT_WORKSPACE_LIST_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-workspace-list",
    skill_md: r#"---
name: "writ-workspace-list"
description: "List all workspaces in the project"
---

# Writ Workspace List

View all workspaces and their associated specs.

## Command

```bash
writ workspace list
```

Shows workspace paths, associated spec IDs, and status. Workspaces provide Level 2 file isolation for agents with competing rewrites of the same file. Most multi-agent work uses same-directory mode (Level 0/1) and does not need workspaces.
"#,
    supporting_files: &[],
};

const WRIT_WORKSPACE_STATUS_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-workspace-status",
    skill_md: r#"---
name: "writ-workspace-status"
description: "Show the status of a specific workspace"
---

# Writ Workspace Status

View detailed status of a workspace.

## Command

```bash
writ workspace status <workspace-path>
```

Shows the workspace's associated spec, owning agent, seal history, and file changes relative to the main project. Useful for monitoring workspace-isolated agents.
"#,
    supporting_files: &[],
};

// ---------------------------------------------------------------------------
// Tier 2-4: Non-Auto-Invoking Skills — SK.4 (CC's 9 skills)
// ---------------------------------------------------------------------------

const WRIT_SPEC_ADD_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-spec-add",
    skill_md: r#"---
name: "writ-spec-add"
description: "Create a new task spec from your task description"
---

# Writ Spec Add

Create a spec to track your task. Writ generates the ID automatically.

## Command

```bash
writ spec add "brief description of your task"
```

Use a short summary (5-10 words). Writ generates a unique hash ID.

## When to Use

- When `writ context` shows no assigned or unclaimed specs
- At the start of a new task
- You typically only need ONE spec per task

## Examples

```bash
writ spec add "OAuth2 authentication for login page"
writ spec add "Fix payment validation for zero-amount transactions"
writ spec add "Add responsive nav menu to Layout"
```
"#,
    supporting_files: &[],
};

const WRIT_FINISH_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-finish",
    skill_md: r#"---
name: "writ-finish"
description: "Converge completed work and commit to git"
---

# Writ Finish

Promotes all completed agent work to a git commit. This is a USER command, not an agent command.

## Command

```bash
writ finish
```

## What It Does

1. Runs seal-tree convergence on all completed, uncommitted specs
2. Materializes merged file content to the working directory
3. Creates a git commit with all changes
4. Marks committed specs so they don't participate in future convergence

## Options

- `--auto` — auto-resolve conflicts (uses most-recent-seal-wins strategy)
- `--dry-run` — preview what would be committed without committing
- `--strategy <name>` — commit strategy: `single` (default), `per-spec`, `grouped`
"#,
    supporting_files: &[SupportingFile {
        filename: "commit-strategies.md",
        content: r#"# Commit Strategies

## single (default)
One git commit for all completed specs. Best for most workflows.

## per-spec
One git commit per spec. Useful when each spec represents an independent feature that should have its own commit in git history.

## grouped
Specs grouped by common directory prefix, one commit per group. Useful for monorepo-style projects where changes cluster by module.
"#,
    }],
};

const WRIT_TASK_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-task",
    skill_md: r#"---
name: "writ-task"
description: "Create a task with workspace isolation for competing rewrites"
---

# Writ Task

Creates a spec + isolated workspace. Use when agents need physical file isolation (competing rewrites of the same code).

## Command

```bash
writ task "description of the task"
```

## When to Use

- When multiple agents will make competing changes to the SAME files
- When you want file isolation between agents (each gets their own copy)
- This is a power-user tool for ~10% of cases

For most multi-agent work, agents can share the same directory. Writ's convergence engine handles overlapping changes automatically.
"#,
    supporting_files: &[SupportingFile {
        filename: "task-naming.md",
        content: r#"# Task Naming

Use clear, descriptive task names:
- "Rewrite auth module — approach A"
- "Add payment processing with Stripe"
- "Refactor database layer to async"

Writ generates a hash ID and a slug from your title. The slug is used for the workspace directory name.
"#,
    }],
};

const WRIT_SUMMARY_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-summary",
    skill_md: r#"---
name: "writ-summary"
description: "Generate a summary of all work done in this session"
---

# Writ Summary

Generates a human-readable summary of all work done across all specs.

## Command

```bash
writ summary
```

## Options

- `--format json` — structured JSON output
- `--format toon` — token-optimized format (default)
"#,
    supporting_files: &[SupportingFile {
        filename: "format-examples.md",
        content: r#"# Output Format Examples

## TOON (default)
Token-optimized notation. 20-33% smaller than JSON. Designed for LLM consumption.

## JSON
Standard JSON. Use `--format json` when you need structured output for scripts or tools.
"#,
    }],
};

const WRIT_RESTORE_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-restore",
    skill_md: r#"---
name: "writ-restore"
description: "Restore working directory to a previous seal's state"
---

# Writ Restore

Rewind the working directory to a previous seal's snapshot. Use when something goes wrong.

## Command

```bash
writ restore <seal-id>
```

## How to Use

1. Find the last known-good seal: `writ log --all`
2. Inspect it: `writ show <seal-id> --diff`
3. Restore: `writ restore <seal-id>`
4. Seal the rollback: `writ seal -s "rolled back to <seal-id>"`

Every seal is immutable. Restoring doesn't delete history — all previous seals remain in the log.
"#,
    supporting_files: &[SupportingFile {
        filename: "rollback-guide.md",
        content: r#"# Rollback Guide

## When to Restore

- Tests fail after your changes
- Convergence produced unexpected results
- You went down the wrong implementation path

## Steps

1. `writ log --all` — find the seal BEFORE things went wrong
2. `writ show <seal-id> --diff` — verify it's the right state
3. `writ restore <seal-id>` — rewind working directory
4. `writ seal -s "rolled back to <seal-id>"` — record the rollback
5. Continue working from the restored state

## Important

- Restore changes your working directory files, NOT the seal history
- All seals (including the bad ones) remain in the log for audit
- After restoring, you're working on the restored state — seal normally from here
"#,
    }],
};

const WRIT_CONVERGE_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-converge",
    skill_md: r#"---
name: "writ-converge"
description: "Preview or apply convergence between specs"
---

# Writ Converge

Preview or apply convergence manually. Usually handled automatically by `writ finish`.

## Commands

```bash
writ converge-all --dry-run              # preview what would be merged
writ converge-all --apply --strategy escalate   # apply with recommended strategy
writ converge <left-spec> <right-spec> --apply  # merge two specific specs
```

## Strategies

- `escalate` (recommended) — auto-resolves confident merges, escalates conflicts
- `three-way-merge` (default) — standard three-way merge
- `most-recent` — prefers the newest seal's version on conflict
"#,
    supporting_files: &[SupportingFile {
        filename: "convergence-strategies.md",
        content: r#"# Convergence Strategies

## escalate (recommended)
Auto-resolves changes above the confidence threshold (0.85). Escalates genuine conflicts for human review. Best for most workflows.

## three-way-merge
Standard three-way merge using genesis tree as base. Reports all conflicts without auto-resolving.

## most-recent
On conflict, prefers the version from the spec with the most recent seal. Simple but may lose earlier work.

## When Convergence Runs

1. **At spec completion** — when an agent calls `writ spec done`, convergence checks for overlapping completed specs
2. **At finish** — `writ finish` runs convergence as a backstop before committing
3. **Manually** — `writ converge-all` for explicit control
"#,
    }],
};

const WRIT_VERIFY_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-verify",
    skill_md: r#"---
name: "writ-verify"
description: "Verify seal chain integrity and cryptographic signatures"
---

# Writ Verify

Verify the integrity of the seal chain.

## Command

```bash
writ verify
```

## Options

- `--format json` — structured verification report
- `--verbose` — show per-seal verification details

Checks content hashes, chain hashes, and Ed25519 signatures for every seal in the chain.
"#,
    supporting_files: &[],
};

const WRIT_DOCTOR_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-doctor",
    skill_md: r#"---
name: "writ-doctor"
description: "Diagnose writ repository health and configuration issues"
---

# Writ Doctor

Run diagnostics on the writ repository.

## Command

```bash
writ doctor
```

Checks: .writ/ integrity, index consistency, spec health, seal chain, git sync status, storage usage.
"#,
    supporting_files: &[],
};

const WRIT_WORKSPACE_CREATE_SKILL: SkillTemplate = SkillTemplate {
    name: "writ-workspace-create",
    skill_md: r#"---
name: "writ-workspace-create"
description: "Create an isolated workspace for parallel development"
---

# Writ Workspace Create

Create a workspace with its own file copy for isolated development.

## Command

```bash
writ workspace create <name>
```

## When to Use

Most multi-agent work doesn't need workspaces — agents share the same directory and convergence handles overlaps. Use workspaces only when you need physical file isolation (competing rewrites).

For the common case, use `writ task` which creates both a spec and a workspace together.
"#,
    supporting_files: &[],
};

// ---------------------------------------------------------------------------
// Template Registry
// ---------------------------------------------------------------------------

/// All skill templates, ordered: Tier 1 (auto-invoke) first, then Tier 2-4.
pub const SKILL_TEMPLATES: &[&SkillTemplate] = &[
    // Tier 1: Auto-invoking (3)
    &WRIT_CONTEXT_SKILL,
    &WRIT_SEAL_SKILL,
    &WRIT_SPEC_DONE_SKILL,
    // Tier 2: Status & Review (4) — Izzy
    &WRIT_STATUS_SKILL,
    &WRIT_DIFF_SKILL,
    &WRIT_LOG_SKILL,
    &WRIT_SHOW_SKILL,
    // Tier 3: Spec Management (4) — Izzy (3) + CC (1)
    &WRIT_SPEC_STATUS_SKILL,
    &WRIT_SPEC_SHOW_SKILL,
    &WRIT_SPEC_REOPEN_SKILL,
    &WRIT_SPEC_ADD_SKILL,
    // Tier 2: Round-Trip (2) — CC
    &WRIT_FINISH_SKILL,
    &WRIT_SUMMARY_SKILL,
    // Tier 3: Recovery & Convergence (2) — CC
    &WRIT_RESTORE_SKILL,
    &WRIT_CONVERGE_SKILL,
    // Tier 3: Diagnostics (2) — CC
    &WRIT_VERIFY_SKILL,
    &WRIT_DOCTOR_SKILL,
    // Tier 3: Workspace (3) — CC (2) + Izzy (2)
    &WRIT_TASK_SKILL,
    &WRIT_WORKSPACE_CREATE_SKILL,
    &WRIT_WORKSPACE_LIST_SKILL,
    &WRIT_WORKSPACE_STATUS_SKILL,
];

/// Count of skills with auto-invoke enabled.
pub fn auto_invoke_count() -> usize {
    3 // writ-context, writ-seal, writ-spec-done
}

// ---------------------------------------------------------------------------
// Generation and Removal — SK.2 (Izzy will refine, CC providing initial impl)
// ---------------------------------------------------------------------------

/// Result of skill generation.
#[derive(Debug, Default, serde::Serialize)]
pub struct SkillGenerateResult {
    pub created: usize,
    pub updated: usize,
    pub skipped: usize,
}

/// Generate skill directories in `.claude/skills/`.
pub fn generate_skills(root: &Path) -> WritResult<SkillGenerateResult> {
    let skills_dir = root.join(".claude").join("skills");
    fs::create_dir_all(&skills_dir)?;

    let mut result = SkillGenerateResult::default();

    for template in SKILL_TEMPLATES {
        let skill_dir = skills_dir.join(template.name);
        fs::create_dir_all(&skill_dir)?;

        // Write SKILL.md
        let skill_path = skill_dir.join("SKILL.md");
        let full_content = format!("{}{}", GENERATED_HEADER, template.skill_md);

        if skill_path.exists() {
            let existing = fs::read_to_string(&skill_path).unwrap_or_default();
            if existing == full_content {
                result.skipped += 1;
                // Still check supporting files
            } else {
                atomic_write(&skill_path, full_content.as_bytes())?;
                result.updated += 1;
            }
        } else {
            atomic_write(&skill_path, full_content.as_bytes())?;
            result.created += 1;
        }

        // Write supporting files
        for sf in template.supporting_files {
            let sf_path = skill_dir.join(sf.filename);
            let sf_content = format!("{}{}", GENERATED_HEADER, sf.content);
            if sf_path.exists() {
                let existing = fs::read_to_string(&sf_path).unwrap_or_default();
                if existing != sf_content {
                    atomic_write(&sf_path, sf_content.as_bytes())?;
                }
            } else {
                atomic_write(&sf_path, sf_content.as_bytes())?;
            }
        }
    }

    Ok(result)
}

/// Remove all writ skill directories from `.claude/skills/`.
pub fn remove_skills(root: &Path) -> WritResult<Vec<String>> {
    let skills_dir = root.join(".claude").join("skills");
    if !skills_dir.exists() {
        return Ok(Vec::new());
    }

    let mut removed = Vec::new();

    for entry in fs::read_dir(&skills_dir)? {
        let entry = entry?;
        let name = entry.file_name().to_string_lossy().to_string();

        // Only remove writ-prefixed directories.
        if name.starts_with("writ-") && entry.path().is_dir() {
            fs::remove_dir_all(entry.path())?;
            removed.push(name);
        }
    }

    // Clean up empty skills directory.
    if skills_dir.exists() {
        if fs::read_dir(&skills_dir)?.next().is_none() {
            let _ = fs::remove_dir(&skills_dir);
        }
    }

    Ok(removed)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_template_count() {
        // 3 Tier 1 (auto-invoke) + 9 CC + 9 Izzy = 21 total.
        assert_eq!(SKILL_TEMPLATES.len(), 21);
    }

    #[test]
    fn test_template_names_unique() {
        let mut names: Vec<&str> = SKILL_TEMPLATES.iter().map(|t| t.name).collect();
        let original_len = names.len();
        names.sort();
        names.dedup();
        assert_eq!(names.len(), original_len, "duplicate skill names found");
    }

    #[test]
    fn test_all_templates_have_content() {
        for t in SKILL_TEMPLATES {
            assert!(!t.skill_md.is_empty(), "skill {} has empty content", t.name);
        }
    }

    #[test]
    fn test_all_names_start_with_writ() {
        for t in SKILL_TEMPLATES {
            assert!(
                t.name.starts_with("writ-"),
                "skill name '{}' must start with 'writ-'",
                t.name
            );
        }
    }

    #[test]
    fn test_auto_invoke_count() {
        assert_eq!(auto_invoke_count(), 3);
    }

    #[test]
    fn test_tier1_skills_have_auto_invoke_frontmatter() {
        let tier1 = &SKILL_TEMPLATES[..3];
        for t in tier1 {
            assert!(
                t.skill_md.contains("autoInvoke: true"),
                "Tier 1 skill '{}' missing autoInvoke: true",
                t.name
            );
        }
    }

    #[test]
    fn test_tier1_skills_have_supporting_files() {
        let tier1 = &SKILL_TEMPLATES[..3];
        for t in tier1 {
            assert!(
                !t.supporting_files.is_empty(),
                "Tier 1 skill '{}' should have at least 1 supporting file",
                t.name
            );
        }
    }

    #[test]
    fn test_generate_creates_directories() {
        let dir = tempdir().unwrap();
        let result = generate_skills(dir.path()).unwrap();

        assert_eq!(result.created, 21);
        assert_eq!(result.skipped, 0);

        for t in SKILL_TEMPLATES {
            let skill_dir = dir.path().join(".claude/skills").join(t.name);
            assert!(skill_dir.exists(), "missing skill dir: {}", t.name);
            assert!(
                skill_dir.join("SKILL.md").exists(),
                "missing SKILL.md in {}",
                t.name
            );
        }
    }

    #[test]
    fn test_generate_idempotent() {
        let dir = tempdir().unwrap();
        generate_skills(dir.path()).unwrap();
        let result = generate_skills(dir.path()).unwrap();

        assert_eq!(result.created, 0);
        assert_eq!(result.updated, 0);
        assert_eq!(result.skipped, 21);
    }

    #[test]
    fn test_generate_supporting_files() {
        let dir = tempdir().unwrap();
        generate_skills(dir.path()).unwrap();

        // writ-context should have reading-context.md
        let ctx_dir = dir.path().join(".claude/skills/writ-context");
        assert!(ctx_dir.join("reading-context.md").exists());

        // writ-seal should have seal-checklist.md
        let seal_dir = dir.path().join(".claude/skills/writ-seal");
        assert!(seal_dir.join("seal-checklist.md").exists());
    }

    #[test]
    fn test_generated_header_present() {
        let dir = tempdir().unwrap();
        generate_skills(dir.path()).unwrap();

        let content =
            fs::read_to_string(dir.path().join(".claude/skills/writ-context/SKILL.md")).unwrap();
        assert!(content.starts_with(GENERATED_HEADER));
    }

    #[test]
    fn test_remove_cleans_writ_skills() {
        let dir = tempdir().unwrap();
        generate_skills(dir.path()).unwrap();

        let removed = remove_skills(dir.path()).unwrap();
        assert_eq!(removed.len(), 21);

        // Skills directory should be cleaned up (empty).
        assert!(!dir.path().join(".claude/skills").exists());
    }

    #[test]
    fn test_remove_preserves_non_writ_skills() {
        let dir = tempdir().unwrap();
        generate_skills(dir.path()).unwrap();

        // Create a non-writ skill.
        let custom = dir.path().join(".claude/skills/my-custom-skill");
        fs::create_dir_all(&custom).unwrap();
        fs::write(custom.join("SKILL.md"), "custom skill").unwrap();

        let removed = remove_skills(dir.path()).unwrap();
        assert_eq!(removed.len(), 21);

        // Custom skill should survive.
        assert!(custom.exists());
        assert!(custom.join("SKILL.md").exists());
    }

    #[test]
    fn test_remove_noop_when_no_skills() {
        let dir = tempdir().unwrap();
        let removed = remove_skills(dir.path()).unwrap();
        assert!(removed.is_empty());
    }

    // -----------------------------------------------------------------------
    // SK.8: Bri's additional unit tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_generate_updates_changed_content() {
        let dir = tempdir().unwrap();
        generate_skills(dir.path()).unwrap();

        // Manually corrupt a SKILL.md so it differs from template.
        let skill_md = dir.path().join(".claude/skills/writ-context/SKILL.md");
        fs::write(&skill_md, "stale content").unwrap();

        let result = generate_skills(dir.path()).unwrap();
        assert_eq!(result.updated, 1, "one skill should be updated");
        assert_eq!(
            result.skipped,
            SKILL_TEMPLATES.len() - 1,
            "remaining skills should be skipped"
        );

        // Verify the file was overwritten with the correct content.
        let content = fs::read_to_string(&skill_md).unwrap();
        assert!(
            content.starts_with(GENERATED_HEADER),
            "updated SKILL.md should start with generated header"
        );
        assert!(
            content.contains("autoInvoke: true"),
            "writ-context should still have autoInvoke after update"
        );
    }

    #[test]
    fn test_all_supporting_files_have_generated_header() {
        let dir = tempdir().unwrap();
        generate_skills(dir.path()).unwrap();

        for t in SKILL_TEMPLATES {
            let skill_dir = dir.path().join(".claude/skills").join(t.name);
            for sf in t.supporting_files {
                let path = skill_dir.join(sf.filename);
                assert!(path.exists(), "{}/{} missing", t.name, sf.filename);
                let content = fs::read_to_string(&path).unwrap();
                assert!(
                    content.starts_with(GENERATED_HEADER),
                    "{}/{} missing generated header",
                    t.name,
                    sf.filename
                );
                // Content should have more than just the header.
                assert!(
                    content.len() > GENERATED_HEADER.len() + 10,
                    "{}/{} has header but no meaningful content",
                    t.name,
                    sf.filename
                );
            }
        }
    }

    #[test]
    fn test_non_auto_invoke_skills_no_auto_invoke_true() {
        // Tier 2-4 skills (index 3+) must NOT contain autoInvoke: true.
        let non_auto = &SKILL_TEMPLATES[3..];
        for t in non_auto {
            assert!(
                !t.skill_md.contains("autoInvoke: true"),
                "non-auto-invoke skill '{}' should not have autoInvoke: true",
                t.name
            );
        }
    }

    #[test]
    fn test_all_skills_have_yaml_frontmatter() {
        for t in SKILL_TEMPLATES {
            let lines: Vec<&str> = t.skill_md.lines().collect();
            assert!(
                lines.len() >= 3,
                "skill '{}' is too short for frontmatter",
                t.name
            );
            assert_eq!(
                lines[0], "---",
                "skill '{}' should start with --- frontmatter delimiter",
                t.name
            );
            // Find closing delimiter (second ---).
            let closing = lines.iter().skip(1).position(|l| *l == "---");
            assert!(
                closing.is_some(),
                "skill '{}' missing closing --- frontmatter delimiter",
                t.name
            );
        }
    }

    #[test]
    fn test_all_skills_have_name_in_frontmatter() {
        for t in SKILL_TEMPLATES {
            let expected = format!("name: \"{}\"", t.name);
            assert!(
                t.skill_md.contains(&expected),
                "skill '{}' frontmatter should contain name field matching template name",
                t.name
            );
        }
    }

    #[test]
    fn test_supporting_files_idempotent() {
        let dir = tempdir().unwrap();
        generate_skills(dir.path()).unwrap();

        // Read all supporting file contents.
        let mut originals: Vec<(String, String, String)> = Vec::new();
        for t in SKILL_TEMPLATES {
            let skill_dir = dir.path().join(".claude/skills").join(t.name);
            for sf in t.supporting_files {
                let path = skill_dir.join(sf.filename);
                let content = fs::read_to_string(&path).unwrap();
                originals.push((t.name.to_string(), sf.filename.to_string(), content));
            }
        }

        // Re-generate — supporting files should be unchanged.
        generate_skills(dir.path()).unwrap();

        for (name, filename, original) in &originals {
            let path = dir.path().join(".claude/skills").join(name).join(filename);
            let content = fs::read_to_string(&path).unwrap();
            assert_eq!(
                &content, original,
                "{}/{} content changed after idempotent re-generation",
                name, filename
            );
        }
    }
}
