//! Slash command template generation for Claude Code.
//!
//! Generates markdown files in `.claude/commands/` that expose writ workflow
//! commands as discoverable slash commands in Claude Code's command palette.
//! All 17 commands are thin wrappers around the CLI — no business logic here.

use std::fs;
use std::path::Path;

use crate::error::WritResult;
use crate::fsutil::atomic_write;

/// Header injected at the top of every generated slash command file.
const GENERATED_HEADER: &str = "<!-- Generated by writ init. Do not edit. -->\n";

/// A slash command template: file name (without `.md`) and markdown content.
pub struct SlashCommandTemplate {
    /// File name without extension, e.g. "writ-context" -> `.claude/commands/writ-context.md`
    pub name: &'static str,
    /// Markdown content for the command file (without the generated header).
    pub content: &'static str,
}

// ---------------------------------------------------------------------------
// Core Workflow (4) — SC.2 (Izzy)
// ---------------------------------------------------------------------------

const WRIT_CONTEXT: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-context",
    content: r#"Show the current writ context for this project.

Run this FIRST at the start of every task to understand project state.

```bash
writ context
```

Returns project state in TOON format (20-33% fewer bytes than JSON).

Options:
- `--format json` — standard JSON output
- `--spec <id>` — scope context to a specific spec
"#,
};

const WRIT_SEAL: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-seal",
    content: r#"Seal the current work as a writ checkpoint.

Run this after each meaningful unit of work to create an immutable snapshot.

```bash
writ seal -s "$ARGUMENTS" --spec <spec-id>
```

Options:
- `-s "<summary>"` — clear description of what you accomplished (required)
- `--spec <id>` — the spec this work belongs to (expected)
- `--agent <id>` — your agent identity (auto-detected if omitted)
- `--paths <file1,file2>` — specific file paths to seal (default: all changes)
- `--tests-passed N --tests-failed M` — include test results

When your task is fully complete, run `writ spec done <spec-id>` instead.
"#,
};

const WRIT_SPEC_ADD: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-spec-add",
    content: r#"Create a new task spec.

```bash
writ spec add --id $ARGUMENTS --title "<description>"
```

Options:
- `--id <spec-id>` — unique identifier for the spec (required)
- `--title "<description>"` — human-readable title (required)
- `--description "<details>"` — optional longer description

After creating a spec, checkpoint your work with `writ seal` and mark it done with `writ spec done`.
"#,
};

const WRIT_SPEC_DONE: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-spec-done",
    content: r#"Mark a spec as complete.

```bash
writ spec done $ARGUMENTS
```

This marks the specified spec as complete and creates a final seal.
The spec moves from `active` to `completed` status.

If only one active spec exists, the ID is auto-detected:
```bash
writ spec done
```

Use this when your task is fully finished. The user will then run `writ finish` to promote the work to a git commit.
"#,
};

// ---------------------------------------------------------------------------
// Status & Review (4) — SC.3 (Lee)
// ---------------------------------------------------------------------------

const WRIT_STATUS: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-status",
    content: r#"Show fleet overview: agents, specs, and recent activity.

```bash
writ status
```

Options:
- `--completed` — show all completed specs in detail
- `--active` — show all in-progress specs in detail
- `--agent <id>` — filter by agent name
- `--spec <id>` — detail view of one spec
- `--watch` — live-updating view (refreshes every 5s)
- `--interval <secs>` — custom refresh interval for watch mode
- `--format <fmt>` — output format: human (default), json, json-compact, toon
"#,
};

const WRIT_DIFF: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-diff",
    content: r#"View file changes tracked by writ.

```bash
writ diff
```

Options:
- `--spec <id>` — changes for a specific spec
- `--agent <id>` — changes by a specific agent
- `--stat` — summary only (files and line counts)
- `--name-only` — file paths only
- `--cached` — completed but uncommitted changes
- `--completed` — include completed specs
- `--all` — all specs including completed
- `--file <path>` — filter to specific file
"#,
};

const WRIT_LOG: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-log",
    content: r#"Show seal history (checkpoints created by agents).

```bash
writ log
```

Options:
- `--spec <id>` — seals for a specific spec only
- `--all` — include seals from all branches (diverged work)
- `--limit <n>` or `-l <n>` — max number of seals to show
- `--format <fmt>` — output format: human (default), json, json-compact, brief
"#,
};

const WRIT_SHOW: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-show",
    content: r#"Inspect a specific seal (checkpoint) in detail.

```bash
writ show $ARGUMENTS
```

The argument is a seal ID (supports short prefix matching, e.g., `writ show abc12`).

Options:
- `--diff` — include the file diff introduced by this seal
- `--format <fmt>` — output format: human (default), json, json-compact, brief
"#,
};

// ---------------------------------------------------------------------------
// Spec Management (3) — SC.3 (Lee)
// ---------------------------------------------------------------------------

const WRIT_SPEC_STATUS: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-spec-status",
    content: r#"List all specs and their current lifecycle state.

```bash
writ spec status
```

Options:
- `--state <state>` — filter by lifecycle state: active, stale, completed, cancelled, archived
- `--format <fmt>` — output format: human (default), json
"#,
};

const WRIT_SPEC_SHOW: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-spec-show",
    content: r#"Show detailed information about a specific spec.

```bash
writ spec show $ARGUMENTS
```

The argument is the spec ID. Displays title, description, status, acceptance criteria, seal count, file scope, and activity timeline.
"#,
};

const WRIT_SPEC_REOPEN: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-spec-reopen",
    content: r#"Reopen a completed spec to resume work on it.

```bash
writ spec reopen $ARGUMENTS
```

The argument is the spec ID. This moves a spec from `completed` back to `active` status. Only works on specs that are completed but not yet committed to git. All previous seals are preserved.
"#,
};

// ---------------------------------------------------------------------------
// Round-Trip (2) — SC.4 (Lee)
// ---------------------------------------------------------------------------

const WRIT_FINISH: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-finish",
    content: r#"Promote completed specs to git commits.

**Note:** This command is for the human user, not agents. Agents should use `writ spec done` instead.

```bash
writ finish
```

Options:
- `--full` — use full PR-style description as commit body
- `--dry-run` — preview what would be committed without committing
- `--yes` or `-y` — skip confirmation prompts
- `--strategy <strategy>` — commit strategy: single (default), per-spec, grouped
- `--auto` — auto mode: commit immediately without prompts
"#,
};

const WRIT_SUMMARY: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-summary",
    content: r#"Generate a commit message or PR description from writ history.

```bash
writ summary
```

Options:
- `--format commit` — concise one-line commit message (default)
- `--format pr` — detailed PR description with spec/agent breakdown
- `--format json` — machine-readable output
- `--format human` — human-readable summary

Commonly used by the human developer:
```bash
git commit -m "$(writ summary --format commit)"
gh pr create --body "$(writ summary --format pr)"
```
"#,
};

// ---------------------------------------------------------------------------
// Recovery & Convergence (2) — SC.4 (Lee)
// ---------------------------------------------------------------------------

const WRIT_RESTORE: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-restore",
    content: r#"Rollback the working directory to a previous seal's state.

```bash
writ restore $ARGUMENTS
```

The argument is a seal ID. Restores files to match the snapshot captured at that seal. Does NOT delete history; all previous seals remain in the log.

Options:
- `--force` — skip the confirmation prompt
- `--format <fmt>` — output format: human (default), json

Use `writ log` to find the right seal, then `writ show <id> --diff` to inspect before restoring.
"#,
};

const WRIT_CONVERGE: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-converge",
    content: r#"Merge diverged branches from parallel agent work.

Two-branch convergence:
```bash
writ converge <left-spec> <right-spec> --apply
```

All-branch convergence:
```bash
writ converge-all --dry-run
writ converge-all --apply --strategy most-complete
```

Strategies:
- `three-way-merge` — default, leaves conflicts for manual resolution
- `most-recent` — prefers the newest version
- `most-complete` — prefers the version with more content

Options:
- `--apply` — apply the merge result to working directory
- `--dry-run` — preview what would be merged without applying
- `--auto-resolve` — auto-apply high-confidence resolutions
- `--format <fmt>` — output format: json (default), json-compact, human
"#,
};

// ---------------------------------------------------------------------------
// Diagnostics (2) — SC.4 (Lee)
// ---------------------------------------------------------------------------

const WRIT_VERIFY: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-verify",
    content: r#"Verify seal chain integrity and cryptographic signatures.

```bash
writ verify
```

Options:
- `--chain` — verify full hash chain from genesis to HEAD
- `--all-chains` — verify HEAD chain plus all spec branch chains
- `--seal <id>` — verify a specific seal by ID or prefix
- `--format <fmt>` — output format: human (default), json
"#,
};

const WRIT_DOCTOR: SlashCommandTemplate = SlashCommandTemplate {
    name: "writ-doctor",
    content: r#"Run a health check on the writ repository.

```bash
writ doctor
```

Checks repository structure, index integrity, config validity, and seal chain health.

Options:
- `--json` — output results as JSON
- `--fix` — attempt to fix detected problems
"#,
};

// ---------------------------------------------------------------------------
// Template registry
// ---------------------------------------------------------------------------

/// All 17 slash command templates in workflow order.
pub const SLASH_COMMAND_TEMPLATES: &[&SlashCommandTemplate] = &[
    // Core Workflow (4)
    &WRIT_CONTEXT,
    &WRIT_SEAL,
    &WRIT_SPEC_ADD,
    &WRIT_SPEC_DONE,
    // Status & Review (4)
    &WRIT_STATUS,
    &WRIT_DIFF,
    &WRIT_LOG,
    &WRIT_SHOW,
    // Spec Management (3)
    &WRIT_SPEC_STATUS,
    &WRIT_SPEC_SHOW,
    &WRIT_SPEC_REOPEN,
    // Round-Trip (2)
    &WRIT_FINISH,
    &WRIT_SUMMARY,
    // Recovery & Convergence (2)
    &WRIT_RESTORE,
    &WRIT_CONVERGE,
    // Diagnostics (2)
    &WRIT_VERIFY,
    &WRIT_DOCTOR,
];

/// Generate all slash command files in `.claude/commands/`.
///
/// Returns the list of file paths that were created or updated (relative to project root).
/// Files are only written if they don't exist or their content has changed, making this
/// idempotent and safe for `writ init --reconfigure`.
pub fn generate_slash_commands(root: &Path) -> WritResult<GenerateResult> {
    let commands_dir = root.join(".claude").join("commands");
    if !commands_dir.exists() {
        fs::create_dir_all(&commands_dir)?;
    }

    let mut created = Vec::new();
    let mut updated = Vec::new();

    for template in SLASH_COMMAND_TEMPLATES {
        let file_path = commands_dir.join(format!("{}.md", template.name));
        let full_content = format!("{}{}", GENERATED_HEADER, template.content);
        let relative_path = format!(".claude/commands/{}.md", template.name);

        if file_path.exists() {
            let existing = fs::read_to_string(&file_path)?;
            if existing != full_content {
                atomic_write(&file_path, full_content.as_bytes())?;
                updated.push(relative_path);
            }
            // Content matches — skip (idempotent).
        } else {
            atomic_write(&file_path, full_content.as_bytes())?;
            created.push(relative_path);
        }
    }

    Ok(GenerateResult { created, updated })
}

/// Remove all writ slash command files from `.claude/commands/`.
///
/// Only removes files with the `writ-` prefix to avoid deleting non-writ commands.
/// Returns the list of removed file paths (relative to project root).
pub fn remove_slash_commands(root: &Path) -> WritResult<Vec<String>> {
    let commands_dir = root.join(".claude").join("commands");
    if !commands_dir.exists() {
        return Ok(Vec::new());
    }

    let mut removed = Vec::new();

    for entry in fs::read_dir(&commands_dir)? {
        let entry = entry?;
        let file_name = entry.file_name();
        let name = file_name.to_string_lossy();
        if name.starts_with("writ-") && name.ends_with(".md") {
            fs::remove_file(entry.path())?;
            removed.push(format!(".claude/commands/{}", name));
        }
    }

    // Clean up empty commands dir.
    if commands_dir.exists() && is_dir_empty(&commands_dir) {
        let _ = fs::remove_dir(&commands_dir);
    }

    Ok(removed)
}

/// Result of generating slash commands.
pub struct GenerateResult {
    /// Files that were newly created.
    pub created: Vec<String>,
    /// Files that existed but were updated with new content.
    pub updated: Vec<String>,
}

impl GenerateResult {
    /// Total number of files affected (created + updated).
    pub fn total(&self) -> usize {
        self.created.len() + self.updated.len()
    }

    /// True if nothing was written (all files already up to date).
    pub fn is_empty(&self) -> bool {
        self.created.is_empty() && self.updated.is_empty()
    }
}

fn is_dir_empty(path: &Path) -> bool {
    fs::read_dir(path)
        .map(|mut entries| entries.next().is_none())
        .unwrap_or(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_template_count() {
        assert_eq!(
            SLASH_COMMAND_TEMPLATES.len(),
            17,
            "expected 17 slash command templates"
        );
    }

    #[test]
    fn test_template_names_unique() {
        let mut names: Vec<&str> = SLASH_COMMAND_TEMPLATES.iter().map(|t| t.name).collect();
        let original_len = names.len();
        names.sort();
        names.dedup();
        assert_eq!(names.len(), original_len, "duplicate template names found");
    }

    #[test]
    fn test_all_templates_have_content() {
        for template in SLASH_COMMAND_TEMPLATES {
            assert!(
                !template.content.is_empty(),
                "template {} has empty content",
                template.name
            );
        }
    }

    #[test]
    fn test_all_templates_start_with_writ() {
        for template in SLASH_COMMAND_TEMPLATES {
            assert!(
                template.name.starts_with("writ-"),
                "template name {} should start with 'writ-'",
                template.name
            );
        }
    }

    #[test]
    fn test_generate_creates_all_files() {
        let dir = tempdir().unwrap();
        let result = generate_slash_commands(dir.path()).unwrap();
        assert_eq!(result.created.len(), 17);
        assert!(result.updated.is_empty());

        for template in SLASH_COMMAND_TEMPLATES {
            let path = dir
                .path()
                .join(".claude")
                .join("commands")
                .join(format!("{}.md", template.name));
            assert!(path.exists(), "missing file for {}", template.name);

            let content = fs::read_to_string(&path).unwrap();
            assert!(
                content.starts_with(GENERATED_HEADER),
                "{} missing generated header",
                template.name
            );
        }
    }

    #[test]
    fn test_generate_idempotent() {
        let dir = tempdir().unwrap();
        generate_slash_commands(dir.path()).unwrap();
        let result2 = generate_slash_commands(dir.path()).unwrap();
        assert!(
            result2.is_empty(),
            "second generate should be a no-op, got {} created {} updated",
            result2.created.len(),
            result2.updated.len()
        );
    }

    #[test]
    fn test_generate_updates_changed_content() {
        let dir = tempdir().unwrap();
        generate_slash_commands(dir.path()).unwrap();

        // Manually modify one file.
        let seal_path = dir
            .path()
            .join(".claude")
            .join("commands")
            .join("writ-seal.md");
        fs::write(&seal_path, "old content").unwrap();

        let result = generate_slash_commands(dir.path()).unwrap();
        assert!(result.created.is_empty());
        assert_eq!(result.updated.len(), 1);
        assert!(result.updated[0].contains("writ-seal"));

        // Content should be restored.
        let content = fs::read_to_string(&seal_path).unwrap();
        assert!(content.starts_with(GENERATED_HEADER));
    }

    #[test]
    fn test_remove_removes_all_writ_files() {
        let dir = tempdir().unwrap();
        generate_slash_commands(dir.path()).unwrap();

        let removed = remove_slash_commands(dir.path()).unwrap();
        assert_eq!(removed.len(), 17);

        // Commands dir should be cleaned up.
        assert!(!dir.path().join(".claude").join("commands").exists());
    }

    #[test]
    fn test_remove_preserves_non_writ_files() {
        let dir = tempdir().unwrap();
        generate_slash_commands(dir.path()).unwrap();

        // Add a non-writ file.
        let custom = dir
            .path()
            .join(".claude")
            .join("commands")
            .join("my-custom-command.md");
        fs::write(&custom, "custom stuff").unwrap();

        let removed = remove_slash_commands(dir.path()).unwrap();
        assert_eq!(removed.len(), 17);

        // Custom file should still exist.
        assert!(custom.exists());
        // Commands dir should NOT be removed (still has files).
        assert!(dir.path().join(".claude").join("commands").exists());
    }

    #[test]
    fn test_remove_noop_when_no_commands_dir() {
        let dir = tempdir().unwrap();
        let removed = remove_slash_commands(dir.path()).unwrap();
        assert!(removed.is_empty());
    }

    // --- Core workflow template content tests (SC.2) ---

    #[test]
    fn test_context_template_says_run_first() {
        assert!(
            WRIT_CONTEXT.content.contains("Run this FIRST"),
            "writ-context must tell agents to run first"
        );
    }

    #[test]
    fn test_context_template_mentions_toon() {
        assert!(
            WRIT_CONTEXT.content.contains("TOON"),
            "writ-context must mention TOON format"
        );
        assert!(
            WRIT_CONTEXT.content.contains("--format json"),
            "writ-context must show JSON fallback"
        );
    }

    #[test]
    fn test_seal_template_has_spec_flag() {
        assert!(
            WRIT_SEAL.content.contains("--spec"),
            "writ-seal must show --spec flag"
        );
    }

    #[test]
    fn test_seal_template_references_spec_done() {
        assert!(
            WRIT_SEAL.content.contains("writ spec done"),
            "writ-seal must reference spec done for task completion"
        );
    }

    #[test]
    fn test_spec_add_template_has_required_flags() {
        assert!(
            WRIT_SPEC_ADD.content.contains("--id"),
            "writ-spec-add must show --id flag"
        );
        assert!(
            WRIT_SPEC_ADD.content.contains("--title"),
            "writ-spec-add must show --title flag"
        );
    }

    #[test]
    fn test_spec_done_template_mentions_finish() {
        assert!(
            WRIT_SPEC_DONE.content.contains("writ finish"),
            "writ-spec-done must reference writ finish as next step"
        );
    }

    #[test]
    fn test_finish_template_warns_agents() {
        assert!(
            WRIT_FINISH.content.contains("human user"),
            "writ-finish must note it's for humans"
        );
    }

    #[test]
    fn test_diff_template_has_correct_flags() {
        let content = WRIT_DIFF.content;
        for flag in &["--spec", "--agent", "--stat", "--name-only", "--cached"] {
            assert!(content.contains(flag), "writ-diff missing {} flag", flag);
        }
        // Must NOT have --full (doesn't exist in our CLI)
        assert!(
            !content.contains("--full"),
            "writ-diff must not reference --full (doesn't exist)"
        );
    }
}
