"""SC.6: Slash command generation integration tests.

Tests the full CLI path for slash command generation/removal via writ init/uninit.
Complements the Rust unit tests in slash_commands.rs with end-to-end verification.
"""

import json
import subprocess
from pathlib import Path

import pytest


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

WRIT_BIN = None
_search = Path(__file__).resolve()
for _ in range(6):
    _search = _search.parent
    for profile in ("release", "debug"):
        candidate = _search / "target" / profile / "writ"
        if candidate.exists():
            WRIT_BIN = str(candidate)
            break
    if WRIT_BIN:
        break

# All 20 expected slash command files (17 original + 3 workspace).
EXPECTED_COMMANDS = [
    "writ-context.md",
    "writ-seal.md",
    "writ-spec-add.md",
    "writ-spec-done.md",
    "writ-status.md",
    "writ-diff.md",
    "writ-log.md",
    "writ-show.md",
    "writ-spec-status.md",
    "writ-spec-show.md",
    "writ-spec-reopen.md",
    "writ-finish.md",
    "writ-summary.md",
    "writ-restore.md",
    "writ-converge.md",
    "writ-verify.md",
    "writ-doctor.md",
    "writ-workspace-create.md",
    "writ-workspace-list.md",
    "writ-workspace-status.md",
]

GENERATED_HEADER = "<!-- Generated by writ init. Do not edit. -->"


def run_writ(args: list, cwd: str, check: bool = True) -> subprocess.CompletedProcess:
    if WRIT_BIN is None:
        pytest.skip("writ binary not found")
    return subprocess.run(
        [WRIT_BIN] + args, capture_output=True, text=True, cwd=cwd, check=check,
    )


def run_git(args: list, cwd: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git"] + args, capture_output=True, text=True, cwd=cwd, check=True,
    )


@pytest.fixture
def git_repo(tmp_path):
    """Clean git repo with Claude Code markers for init to detect."""
    path = tmp_path
    run_git(["init"], str(path))
    run_git(["config", "user.email", "test@test.com"], str(path))
    run_git(["config", "user.name", "Test User"], str(path))
    (path / "README.md").write_text("# Project\n")
    # Create .claude dir + CLAUDE.md so init detects Claude Code
    (path / "CLAUDE.md").write_text("# My Project\n")
    (path / ".claude").mkdir()
    (path / ".claude" / "settings.json").write_text(json.dumps({
        "permissions": {"allow": ["Bash(npm *)"], "deny": []}
    }, indent=2))
    run_git(["add", "."], str(path))
    run_git(["commit", "-m", "initial"], str(path))
    return path


@pytest.fixture
def bare_git_repo(tmp_path):
    """Clean git repo WITHOUT Claude Code markers."""
    path = tmp_path
    run_git(["init"], str(path))
    run_git(["config", "user.email", "test@test.com"], str(path))
    run_git(["config", "user.name", "Test User"], str(path))
    (path / "README.md").write_text("# Project\n")
    run_git(["add", "."], str(path))
    run_git(["commit", "-m", "initial"], str(path))
    return path


# ---------------------------------------------------------------------------
# SC.6: Slash command generation tests
# ---------------------------------------------------------------------------

class TestSlashCommandGeneration:
    """writ init generates all 20 slash command files."""

    def test_init_generates_all_17_commands(self, git_repo):
        """writ init creates all 20 slash command files in .claude/commands/."""
        path = git_repo
        run_writ(["init", "--yes"], str(path))

        commands_dir = path / ".claude" / "commands"
        assert commands_dir.is_dir()

        for cmd_file in EXPECTED_COMMANDS:
            file_path = commands_dir / cmd_file
            assert file_path.exists(), f"Missing slash command: {cmd_file}"

    def test_each_file_has_generated_header(self, git_repo):
        """Every generated file starts with the generated header comment."""
        path = git_repo
        run_writ(["init", "--yes"], str(path))

        commands_dir = path / ".claude" / "commands"
        for cmd_file in EXPECTED_COMMANDS:
            content = (commands_dir / cmd_file).read_text()
            assert content.startswith(GENERATED_HEADER), (
                f"{cmd_file} missing generated header"
            )

    def test_each_file_contains_correct_command(self, git_repo):
        """Each file references the correct writ command."""
        path = git_repo
        run_writ(["init", "--yes"], str(path))

        commands_dir = path / ".claude" / "commands"
        # Map file names to expected CLI command keywords
        command_keywords = {
            "writ-context.md": "writ context",
            "writ-seal.md": "writ seal",
            "writ-spec-add.md": "writ spec add",
            "writ-spec-done.md": "writ spec done",
            "writ-status.md": "writ status",
            "writ-diff.md": "writ diff",
            "writ-log.md": "writ log",
            "writ-show.md": "writ show",
            "writ-spec-status.md": "writ spec status",
            "writ-spec-show.md": "writ spec show",
            "writ-spec-reopen.md": "writ spec reopen",
            "writ-finish.md": "writ finish",
            "writ-summary.md": "writ summary",
            "writ-restore.md": "writ restore",
            "writ-converge.md": "writ converge",
            "writ-verify.md": "writ verify",
            "writ-doctor.md": "writ doctor",
            "writ-workspace-create.md": "writ workspace create",
            "writ-workspace-list.md": "writ workspace list",
            "writ-workspace-status.md": "writ workspace status",
        }
        for cmd_file, keyword in command_keywords.items():
            content = (commands_dir / cmd_file).read_text()
            assert keyword in content, (
                f"{cmd_file} should contain '{keyword}'"
            )


class TestSlashCommandReconfigure:
    """writ init --reconfigure overwrites existing slash commands."""

    def test_reconfigure_updates_commands(self, git_repo):
        """--reconfigure regenerates slash command files."""
        path = git_repo
        run_writ(["init", "--yes"], str(path))

        # Tamper with a command file
        seal_cmd = path / ".claude" / "commands" / "writ-seal.md"
        seal_cmd.write_text("tampered content\n")

        run_writ(["init", "--yes", "--reconfigure"], str(path), check=False)

        # File should be restored with generated header
        content = seal_cmd.read_text()
        assert content.startswith(GENERATED_HEADER)
        assert "tampered" not in content


class TestSlashCommandRemoval:
    """writ uninit removes only writ-prefixed command files."""

    def test_uninit_removes_all_writ_commands(self, git_repo):
        """uninit removes all 20 writ-*.md files."""
        path = git_repo
        run_writ(["init", "--yes"], str(path))

        commands_dir = path / ".claude" / "commands"
        # Verify they exist first
        writ_files = [f for f in commands_dir.iterdir() if f.name.startswith("writ-")]
        assert len(writ_files) == 20

        run_writ(["uninit", "--force"], str(path))

        # All writ commands should be gone
        if commands_dir.exists():
            remaining = [f for f in commands_dir.iterdir() if f.name.startswith("writ-")]
            assert len(remaining) == 0

    def test_uninit_preserves_non_writ_commands(self, git_repo):
        """uninit leaves non-writ command files alone."""
        path = git_repo
        run_writ(["init", "--yes"], str(path))

        # Add a non-writ command file
        commands_dir = path / ".claude" / "commands"
        custom_cmd = commands_dir / "my-custom-command.md"
        custom_cmd.write_text("# My Custom Command\nDo something.\n")

        run_writ(["uninit", "--force"], str(path))

        # Custom command should survive
        assert custom_cmd.exists()
        assert custom_cmd.read_text() == "# My Custom Command\nDo something.\n"


class TestSlashCommandNoClaude:
    """Slash commands not generated when Claude Code not detected."""

    def test_no_commands_without_claude(self, bare_git_repo):
        """writ init --no-claude skips slash command generation."""
        path = bare_git_repo
        run_writ(["init", "--yes", "--no-claude"], str(path))

        commands_dir = path / ".claude" / "commands"
        if commands_dir.exists():
            writ_files = [f for f in commands_dir.iterdir() if f.name.startswith("writ-")]
            assert len(writ_files) == 0, (
                f"Found writ commands without Claude Code: {writ_files}"
            )


class TestMcpJsonGeneration:
    """writ init generates .mcp.json for MCP server discovery."""

    def test_init_creates_mcp_json(self, git_repo):
        """writ init creates .mcp.json with correct server config."""
        path = git_repo
        run_writ(["init", "--yes"], str(path))

        mcp_path = path / ".mcp.json"
        assert mcp_path.exists(), ".mcp.json not created during init"

        config = json.loads(mcp_path.read_text())
        assert "mcpServers" in config
        assert "writ" in config["mcpServers"]
        server = config["mcpServers"]["writ"]
        assert server["command"] == "writ"
        assert "mcp-serve" in server["args"]

    def test_uninit_removes_mcp_json(self, git_repo):
        """writ uninit removes .mcp.json."""
        path = git_repo
        run_writ(["init", "--yes"], str(path))
        assert (path / ".mcp.json").exists()

        run_writ(["uninit", "--force"], str(path))
        assert not (path / ".mcp.json").exists()

    def test_no_mcp_json_without_claude(self, bare_git_repo):
        """writ init --no-claude skips .mcp.json generation."""
        path = bare_git_repo
        run_writ(["init", "--yes", "--no-claude"], str(path))
        assert not (path / ".mcp.json").exists()
